version: '3.3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'music-dev'
      MYSQL_USER: 'usr-music'
      MYSQL_PASSWORD: 'pwd-music'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3380:3306'
    expose:
      - '3306'